### ISSUE TITLE
iconGenie

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#13]
内容
---

マルチプラットフォーム用で使えるアイコンの作成 (iOS, Android, MacOS, Windows)

参考
https://v1.quasar.dev/icongenie/introduction

**Comment by hayato0309** [comment]
@hirotada-t
[blokee_logo_favicon.zip](https://github.com/Recursion-Group-P/blokee/files/8836909/blokee_logo_favicon.zip) 
こちらがロゴとファビコンのデータになります！

**Comment by tkwonn** [comment]
![Screen Shot 2022-06-05 at 23 49 07](https://user-images.githubusercontent.com/66197642/172110332-6468a364-1dc6-4976-a63e-e66efea93527.png)

こちらやっておきました！
