### ISSUE TITLE
styling: faqページ

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#15]
内容
---

FAQページのヘッダー（見出し）と説明文のスタイリングはもう少しこだわれそうな気がします。
今まで反映してきた機能（リプレイやCPU対戦、などなど）について書くのもOKですし、Game Ruleももう少し詳細に書けるかと。

**Comment by tkwonn** [comment]
こちらまだ追加で入れる機能がありそうなので、すべて実装してからFAQに入れたほうがいい内容を決めましょう。

**Comment by hayato0309** [comment]
追加で、、
FAQといいつつ中身はGame Rulesがメインなので、サイドバーでの表示方法は検討してもいいかもですね！
