### ISSUE TITLE
feat/piece/button

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#19]
内容
---
オプションのボタンを押して、戻ってもその形が残る状態にする（カードの中にも反映される）
PlayerクラスのremainingPiecesにもそれが反映されるように状態管理してください。

考えられる方法
---

ピースAlterでフリップしたり回転した後、変更を上書きできるボタンを追加し、新しいピースの座標をストアを通して該当するプレイやーのremainingPiecesに反映させる。
達成条件としましては、ストアのプレイヤーのremainingPiecesが更新されていることです。
プルリクを送る際はそこが明確にわかるようにコンソールか何かで出力結果を示していただけると助かります。

**Comment by hayato0309** [comment]
メモ
* フリップ後のCからの相対的なCoordinateを計算するロジックの作成
* 90度回転後(左右)のCからの相対的なCoordinateを計算するロジックの作成

**Comment by tkwonn** [comment]
![Screen Shot 2022-05-31 at 18 15 08](https://user-images.githubusercontent.com/66197642/171310847-2925bc62-5e14-4e8f-ad01-131064cd2724.png)

細かいですが、ピースの描画開始点の中心点が合っていないようですね。あと、画面を狭めるとカードからはみ出してしまいました。
