### ISSUE TITLE
リポジトリの管理について

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#2]
ブランチ削除・マージ処理は僕の方でやります。
それ以外はやっていただいて構いません。

Issue名と同じブランチ名を切ってください。
何度もすみませんが、少し以前のリポジトリでmainが消え去っていた、、（原因がわからず）のと複雑になっていたため新たにこちらのリポジトリで作業してください。

みなさんにやっていただきたいこと
---------------
ローカルに持ってくる
```
git clone <developブランチのssh>
```

```
npm install (node_modules取得）
```

実行
```
quasar dev
```
をもう一度お願いします。

-----------------

@hayato0309 さんのプルリクエストは反映させてあるので、Issueに追加したデザインの仕上げをこちらのIssue #3 を元にプルリクを送ってください。

@hirotada-t こちらのIssue #4 を元に修正版をfeat/pages/Settingsブランチを切ってから送ってください。

@hiroto0222 すでに取り組んでいたら申し訳ないのですが、こちらのIssue #1 を元にfeat/pages/Homeというブランチを切ってプルリクを送ってください。

リモートの最新版を取得する
---------------
```
git pull origin develop（ブランチ名）--rebase
```
ブランチを切ってそのブランチに移動
----------------
```
git switch -c ブランチ名
```

スタンプで反応くださるとblokeeリポジトリを削除します。（ややこしいので）

**Comment by hirotada-t** [comment]
まとめていただいてありがとうございます。

MTGで理解したつもりでしたが、不十分でした。
今後はこちらも確認しながら進めていきます。
