### ISSUE TITLE
feat/game/judgement

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#29]
内容
---

- [x] プレイヤーのスコア表示、ピースを置くごとにそれが反映されるようにする
- [x] タイマーの起動と終了
- [x] 勝利判定のロジック
- [x] ゲーム終了後のウィンドウ

**Comment by hayato0309** [comment]
メモ

### ゲームの終了
* 全てのPlayerがPass（もしくはSurrender）したときゲームが終了する（playerクラスにpassedみたいなプロパティを持たせる）
* 全てのピースがおけた場合もplayerのpassedをtrueに設定する
* timeが0になった場合もplayerのpassedをtrueに設定する
※PlayerArea内にPassボタンの追加が必要

### スコア計算
> また、自分のピースを全部置くことができたプエイヤーは『+15点』、さらに1マスのピースであがった場合はボーナスとして『+5点』となります。

https://dandeliongameblog.com/blokus/

**Comment by tkwonn** [comment]
今週は、ローカル対ローカルの部分とUIの修正（モバイル・デスクトップ）を行うので、もし負担が多いようであったらこちらのIssueにどなたかヘルプで入れるので、おっしゃってください！

**Comment by tkwonn** [comment]
> * 全てのPlayerがPass（もしくはSurrender）したときゲームが終了する（playerクラスにpassedみたいなプロパティを持たせる）
> * timeが0になった場合もplayerのpassedをtrueに設定する

特定のプレイやーだけもうピースを置けなくなったケース：
availableMovesがなくなったのを確認して、playerクラスのoutOfGame = falseがtrueに切り替わるようにする？
プレイやーのターンを切り替える時に次のプレイやーのoutOfGameがtrueであれば、そのプレイヤーを飛ばしてその次のプレイやーにターンを切り替えるとか？

> * 全てのピースがおけた場合もplayerのpassedをtrueに設定する

すべてのピースが置けたらその時点でゲーム終了？

**Comment by tkwonn** [comment]
各ユーザの手持ちのピースの状態をもっているので、毎回勝利判定をする必要はなさそう。
ゲーム終了の考えられるケースとしては、
- あるプレイヤーがピースをすべて使い切った。
- 全員のタイマーが０になった。
- 全員Passせざるを得なくなった（これはあまりなさそう。。）

**Comment by tkwonn** [comment]
ゲーム終了後のモーダルウィンドウに必要なもの

- 設定画面に戻る
- もう一度同じ設定でプレイ
- リプレイ（これは今go to replayとして置いてあるボタンをそのまま使えそう、ページ遷移しているから）
- ここに各プレイヤーの得点、順位、残り秒数、残っているピースのマスの数とかも表示できたら面白そう。

**Comment by tkwonn** [comment]
@hayato0309 
>＜Passのままでいいと思う理由＞
・Surrenderは「降参する。負けを認める。」という意味。
・例えば Player1がSurrenderした後すぐに他のPlayerもSurrenderした場合、Player1が最初にSurrenderしたにもかかわらず、残りのピースのセル数によってはPlayer1が勝つ可能性もある（最初に「負けを認めた」のに勝ってしまうという違和感）
・であれば、SurrenderではなくPassのままにして、「Passするとこの後はピースを配置することはできないよ」という注意書きを表示するのが良さそう


僕もPassのままでいいと思います。
ちなみにこちらはどういう意味でしょうか？
>SurrenderではなくPassのままにして、「Passするとこの後はピースを配置することはできないよ」という注意書きを表示するのが良さそう

一生おけなくなるは少し違う気がしますし、このターンおけなくなるはPassという単語の意味から明快だと思いました。

**Comment by hayato0309** [comment]
@tkwonn 
> 今週は、ローカル対ローカルの部分とUIの修正（モバイル・デスクトップ）を行うので、もし負担が多いようであったらこちらのIssueにどなたかヘルプで入れるので、おっしゃってください！

ありがとうございます！
現状、
* プレイヤーのスコア表示、ピースを置くごとにそれが反映されるようにする
* タイマーの起動と終了
は実装完了しており、水曜のMTGまでには全部完了すると思っています。

> 特定のプレイやーだけもうピースを置けなくなったケース：
availableMovesがなくなったのを確認して、playerクラスのoutOfGame = falseがtrueに切り替わるようにする？
プレイやーのターンを切り替える時に次のプレイやーのoutOfGameがtrueであれば、そのプレイヤーを飛ばしてその次のプレイやーにターンを切り替えるとか？

はい、そんな感じを想定しています！
ただ「availableMovesがなくなったのを確認して」ではなく、outOfGameをtrueにするのは、PlayerがPassをした時か、時間切れになった時かにしようと思っていました。
blokeeでは、ピースを置ける可能性が０だとしてもアプリ側でPassにせずに、Playerが自分でPassにする必要がありました。（おける可能性が残っている場合も、残ってない場合も最後までPlayerが考える必要があるので、その方がゲーム的にも面白いのかなと考えています。）

> すべてのピースが置けたらその時点でゲーム終了？

例えばPlayer1が全てのピースをおけたとして、Player2が持っている残り一つのピースがおける状態であれば、
Player2にもターンを回したいと思っています。

例
・Player1
　　・残りピース：なし
　　・最後に置いたピース：２マス
　　・残り時間：30秒
・Player2
　　・残りピース：なし
　　・最後に置いたピース：１マス
　　・残り時間：50秒

もしPlayer1が全ピース置いた時点でゲーム終了すると、Player2が勝てたはずなのに負けてしまう（自分が何番目にプレイするかによってどれだけ有利かが決まる）ので、全ピース置けた段階でゲーム終了にはしない方がいいと思っています。

>・あるプレイヤーがピースをすべて使い切った。

上記の通りです！

> ・全員のタイマーが０になった。

いいと思います！

> ・全員Passせざるを得なくなった（これはあまりなさそう。。）

昨日プレイしてて最終的に全員Passになったので全然起こると思います！
> 一生おけなくなるは少し違う気がしますし、このターンおけなくなるはPassという単語の意味から明快だと思いました。

見本のゲーム（blokee）のルールだと、一回Passすると一生置けなくなるんですよ。。
あと、ゲームの性質を考慮しても、一回Passするとその後はずっと置けない仕様でいいのではないかと思っています。
（Passしても自分の角が増えるわけではないため）

> ゲーム終了後のモーダルウィンドウに必要なもの
・設定画面に戻る
・もう一度同じ設定でプレイ
・リプレイ（これは今go to replayとして置いてあるボタンをそのまま使えそう、ページ遷移しているから）
・ここに各プレイヤーの得点、順位、残り秒数、残っているピースのマスの数とかも表示できたら面白そう。

こちらまさにそんな感じで想定しました！

**Comment by tkwonn** [comment]
なるほど、平等にするか、一回の試合時間を短くするかどちらかを選ぶかですね。
ちなみにBlokusは先にプレイしたプレイヤーと最初にボードの中心部分に自分のピースを置けた人が有利になるらしいです

見本のゲームのPassやってみました。なるほど、これおそらくオンライン対戦だからってのもあるかもですね。。

他のお二人の意見も聞きたいですが、@hayatoさんがおっしゃられるように水曜日までに完成させておきたいので、火曜までにコメントがなければ、ひとまず@hayatoさんが考えるロジックで取り組んでしまって大丈夫だと思います！

**Comment by hayato0309** [comment]
06/07 JST 7:00AM時点 追加実装箇所

* Passをクリックした後にplayerのoutOfGameをtrueに更新
  * timer停止 
* timerが0になったときにplayerのoutOfGameをtrueに更新

一旦簡易的に以下のように表示
<img width="366" alt="スクリーンショット 2022-06-07 6 24 59" src="https://user-images.githubusercontent.com/45285649/172251891-fe72ca78-9c52-44f2-8792-0eb940f3b867.png">

これから実装すること
* outOfGameが trueになったユーザーにゲーム上の操作をできないようにする（PlayerAreaの中をクリックできないようにさせる？）
* 全てのplayerのoutOfGameがtrueになったときに、ゲームが終了する
* ゲームが終了したらモーダルを表示させる

**Comment by hayato0309** [comment]
### 今後詰めたいことメモ
1. ConfirmPass => YesのあとPlayerArea内に何を表示させる？（PieceSelector? PieceAlter? それとも別の何か?）
