### ISSUE TITLE
feat/pages/FAQ

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#3]
FAQページはもうデザインを固めてしまって問題ないと思うので、デザインを完成系に近づけていただきたいです。

**Comment by hayato0309** [comment]
@tkwonn 
古いリポジトリの方で、
> メモ：後でスタイルを調整する際に、文章を他のファイルから参照するようにする。

というメモをいただいてましたが、こちらも合わせてこのIssueの中で実装で問題ないでしょうか？

**Comment by tkwonn** [comment]
@hayato0309 そうですねー、思ったんですがあまり良いファイルの場所がわからなかったので、configでもないしutilsでもなさそう、、なので一旦保留でいいです！

**Comment by hayato0309** [comment]
@tkwonn 
ファイルの場所難しいですよね、、
こちらでも色々調べてみたのですが、Vuexのstore/ディレクトリの中はいかがでしょうか？
store/の中に、faq_consts.jsのようなファイルを作成して、全部そこに入れるとか

**Comment by tkwonn** [comment]
storeフォルダはVuexなどでいう可変な状態管理の場所なので、文章などの変わらない値を入れる場所ではない感じなんですよね。
とりあえず、FAQの文章はそのままのファイルで問題ないです。
