### ISSUE TITLE
styling: HomePage

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-P/blokee#46]

**Comment by tkwonn** [comment]
内容
---

サイズ、色の異なるピースをいくつか表示（デザインはお任せします）

https://animejs.com/

こちらのLine Drawingを使用してBlokeeと表示させるのもいいかもしれないですね。
https://animejs.com/documentation/#lineDrawing

こういうのも面白そう。
https://animejs.com/documentation/#gridAxisStaggering

今回のIssueとは関係ないですが、こういうのをGameOverWindowの最終スコアに反映してみるのもおもしろそうですよね。
https://animejs.com/documentation/#round

**Comment by tkwonn** [comment]
こちらのCSSだけでアニメーションを行なっているものも参考になりそうです。

https://codepen.io/juliangarnier/pen/kxGRvV
