### ISSUE TITLE
feat/game/judgement/score

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-P/blokee#47]
内容
---

- [x] 勝利判定のロジック
- [x] スコア計算
- [x] ゲーム終了後のウィンドウ

**Comment by tkwonn** [comment]
src/model/evaluation.jsにてゲームの勝利判定ロジックを書いてください。

達成条件
---

以下の条件が満たされた場合、CheckwinnerメソッドはTrueを返します。
CheckwinnerメソッドをもとにStoreのWinnerExistのブーリアン値を変えてください。

・全てのプレイヤーがOUT OF GAMEになったら（Passを全員が使ったOR時間切れ）

それと、
>あるプレイヤーがすべてのピースを使用してから1周回った。

こちらですが、CPU対戦ができた場合、設定画面でNumber of playersの値に合わせて、ユーザの数とCPUの数を選択できるようにしたいと思っています。

例) Number of player = 4, human = 2, cpu = 2

そのときに、Playerの順序も決めれるようにしたらいいかなと思いました。というのは、ゲームは先行が有利になってしまいがちで、このゲームも実際に先行が有利だと言われているからですね。。

あと、個人的にはCPU対CPUの機能もつけたいと思っていて、先行＋最初に真ん中に自分のピースを置けたほうが勝つと言われているみたいなので、それが本当なのか見てみたいですよね。

getFinalResult（メソッド名こちらに変えましょう）は、各プレイヤーの最終スコアと終了時の残りタイムを返します。
こちらは、GameOverWindow.vueにて取得し、各プレイヤーの情報を反映させましょう。

@hayato0309  @hirotada-t さんには別のIssueを任せているので、こちらひとりになってしまいますが、お願いします！

**Comment by hayato0309** [comment]
@tkwonn 
ありがとうございます！
一点確認したいことがあります。
後半の「CPU対戦ができた場合」以降の部分ですが、これによって何か実装方法や仕様が大きく変わりますでしょうか？

> 以下の条件が満たされた場合、CheckwinnerメソッドはTrueを返します。
CheckwinnerメソッドをもとにStoreのWinnerExistのブーリアン値を変えてください。
・全てのプレイヤーがOUT OF GAMEになったら（Passを全員が使ったOR時間切れ）

この部分はすごくクリアなのですが、CPU対戦を想定することで、実装内容に変更点があるのかなと思いまして...

よろしくお願いします🙇‍♂️

**Comment by tkwonn** [comment]
＠hayato0309 
CPU対戦が実装されても、ゲームの勝利判定に関するロジックは変わりません。
逆にCPU対戦の実装が、ローカル対ローカルでのゲームのようになるように合わせないといけないです。

変わるのは、設定画面とそれに伴うStoreでの処理くらいです。

**Comment by hayato0309** [comment]
@tkwonn 
ありがとうございます！
であればこのIssue内で実装することは、当初のものから変更なしということですね！
（正しく理解できているといいのですが）
