### ISSUE TITLE
layout: Font

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#52]
内容
---

サイトのフォントをデフォルトよりかは変えたほうがいいかと思いました。
みなさんのおすすめするフォントとかあれば、教えてほしいです！

以下のサイトの中から決めてもいいかもです。
https://xd.adobe.com/ideas/principles/web-design/best-modern-fonts-for-websites/

**Comment by hayato0309** [comment]
僕もフォント変えたいなと思ってました。
これとかいかがでしょう？
https://fonts.google.com/specimen/Quicksand

**Comment by tkwonn** [comment]
@hayato0309 了解です！
@hiroto0222 @hirotada-t みなさんはどう思いますか？
