### ISSUE TITLE
fix: desktop

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#62]
内容
---

以下のコマンドでデスクトップ版を試してみてください。

```
quasar dev -m electron
```

いくつかバグやスタイリングの崩れがありました

デスクトップ版ではナブバーにQuitボタンを入れたのですが、そちらの配置がおかしい（いらなかったら取り除いたもよい）
レスポンシブになっていない

Breakpoint
https://v1.quasar.dev/style/breakpoints#introduction

**Comment by hirotada-t** [comment]
- [x] プレイヤーエリアのボタン位置
 - [x] FAQとQUITボタンの位置
 - [x] リプレイから戻るボタン
 - [x] リプレイのレスポンシブ対応（ボタン）
