### ISSUE TITLE
fix: mobile

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/blokee#63]
内容
---

以下のコマンドでAndroid版を試してみてください (Android StudioのEmulatorを同時に起動）

```
quasar dev -m cordova -T android
```

スタイリングの部分で気になる部分がいくつかあった（設定画面のCardの下に余白が欲しいなど）

Breakpoint
https://v1.quasar.dev/style/breakpoints#introduction

**Comment by hiroto0222** [comment]
```
quasar dev -m android --ide
```
のコマンドで自分の携帯 (Google Pixel 6) でアプリを起動してみたところ、正常に動きました。
自分の携帯の画面が大きめだからかもしれませんが、スタイリングに関して気になる点は得にありませんでした。

**Comment by tkwonn** [comment]
GameOverViewのスタイルが崩れていた

**Comment by tkwonn** [comment]
こちらも解決されたので、クローズします！
