### ISSUE TITLE
手持ちピースが1もしくは0個になった時にPlayerAreaのレイアウトが崩れる

### ISSUE THREAD

**Issue by hayato0309** [Recursion-Group-P/blokee#66]
以下の条件でPlayerAreaのレイアウトが崩れる。

残りピースが1つの時
・PlayerAreaが少し内側に寄る
<img width="1437" alt="スクリーンショット 2022-06-15 22 16 57" src="https://user-images.githubusercontent.com/45285649/173836854-66c97151-0c58-4b23-b79e-d9f847150e74.png">

全て使い切った時
・PlayerAreaがBoardに重なる
<img width="1440" alt="スクリーンショット 2022-06-15 22 17 48" src="https://user-images.githubusercontent.com/45285649/173836909-146fd158-e6b0-45c6-bef5-a3eb8818a1ca.png">

**Comment by hirotada-t** [comment]
修正済み
